[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[env]
PHUGLEE_AUTH_DISABLED = "1"

[deploy]
startCommand = "sh scripts/docker-entrypoint.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1